// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package orm

import (
	"database/sql"
)

type Calendar struct {
	ID        int64        `json:"id"`
	NameKey   string       `json:"name_key"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}
