// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package orm

import (
	"context"
)

type Querier interface {
	GetCalendarByID(ctx context.Context, nameKey string) (Calendar, error)
	UpsertCalendar(ctx context.Context, nameKey string) (Calendar, error)
}

var _ Querier = (*Queries)(nil)
